# Generated by Django 3.2.4 on 2021-06-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(max_length=512)),
                ('is_lent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Lendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendment', to='core.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendment', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('UNSET', '--unset--'), ('LEARNER', 'learner'), ('STUDENT', 'student'), ('PENSIONER', 'pensioner'), ('WORKER', 'worker')], default='UNSET', max_length=30)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_type', to='core.borrower')),
            ],
        ),
    ]
