# Generated by Django 3.2.4 on 2021-06-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowertype',
            name='borrower',
        ),
        migrations.AddField(
            model_name='borrower',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='borrower', to='core.borrowertype'),
            preserve_default=False,
        ),
    ]
