# Generated by Django 3.2.4 on 2021-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210604_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='type',
            field=models.CharField(choices=[('UNSET', '--unset--'), ('LEARNER', 'learner'), ('STUDENT', 'student'), ('PENSIONER', 'pensioner'), ('WORKER', 'worker')], default='UNSET', max_length=30),
        ),
        migrations.DeleteModel(
            name='BorrowerType',
        ),
    ]
