# Generated by Django 3.2.4 on 2021-06-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210604_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='type',
            field=models.CharField(choices=[('UNSET', '--unset--'), ('LEARNER', 'uczeń'), ('STUDENT', 'student'), ('PENSIONER', 'emeryt'), ('WORKER', 'pracownik')], default='UNSET', max_length=30),
        ),
    ]
