# Generated by Django 3.2.4 on 2021-06-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='film',
            new_name='book',
        ),
    ]
